daemon: true

http:
    no_tls: true
    use_gzip: false

workers:
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']

    # messenger_consume_async:
    #     cmd: ['symfony', 'console', 'messenger:consume', 'async']
    #     watch: ['config', 'src', 'templates', 'vendor/composer/installed.json']

    # docker_compose: ~
