<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tag, Ticket, Ticket Task, Ticket Status';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
        CREATE TABLE tag (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX TAG_UNIQ_NAME ON tag (name)');
        $this->addSql(<<<SQL
        CREATE TABLE ticket (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            title VARCHAR(255) NOT NULL,
            description TEXT DEFAULT NULL,
            display_order INT DEFAULT 0 NOT NULL,
            project_id INT NOT NULL,
            status_id INT NOT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql('CREATE INDEX IDX_97A0ADA3166D1F9C ON ticket (project_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA36BF700BD ON ticket (status_id)');
        $this->addSql(<<<SQL
        CREATE TABLE ticket_tag (
            ticket_id INT NOT NULL,
            tag_id INT NOT NULL,
            PRIMARY KEY (ticket_id, tag_id)
        )
        SQL);
        $this->addSql('CREATE INDEX IDX_F06CAF700047D2 ON ticket_tag (ticket_id)');
        $this->addSql('CREATE INDEX IDX_F06CAFBAD26311 ON ticket_tag (tag_id)');
        $this->addSql(<<<SQL
        CREATE TABLE ticket_status (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            display_order INT NOT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql(<<<SQL
        CREATE TABLE ticket_task (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            description TEXT NOT NULL,
            is_finished BOOLEAN NOT NULL,
            ticket_id INT NOT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql('CREATE INDEX IDX_60A5CE1D700047D2 ON ticket_task (ticket_id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA36BF700BD FOREIGN KEY (status_id) REFERENCES ticket_status (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_tag ADD CONSTRAINT FK_F06CAF700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket_tag ADD CONSTRAINT FK_F06CAFBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket_task ADD CONSTRAINT FK_60A5CE1D700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_2fb3d0ee989d9b62');
        $this->addSql('ALTER TABLE project DROP slug');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3166D1F9C');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA36BF700BD');
        $this->addSql('ALTER TABLE ticket_tag DROP CONSTRAINT FK_F06CAF700047D2');
        $this->addSql('ALTER TABLE ticket_tag DROP CONSTRAINT FK_F06CAFBAD26311');
        $this->addSql('ALTER TABLE ticket_task DROP CONSTRAINT FK_60A5CE1D700047D2');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_tag');
        $this->addSql('DROP TABLE ticket_status');
        $this->addSql('DROP TABLE ticket_task');
        $this->addSql('ALTER TABLE project ADD slug VARCHAR(255) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_2fb3d0ee989d9b62 ON project (slug)');
    }
}
