<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'User';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
        CREATE TABLE "user" (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(255) NOT NULL,
            roles JSONB NOT NULL,
            password VARCHAR(255) DEFAULT NULL,
            first_name VARCHAR(255) DEFAULT NULL,
            last_name VARCHAR(255) DEFAULT NULL,
            position VARCHAR(255) DEFAULT NULL,
            is_active BOOLEAN NOT NULL, PRIMARY KEY (id))
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "user"');
    }
}
