<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CommunicationChannel, Contact, Company & relations';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<SQL
        CREATE TABLE communication_channel (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            type VARCHAR(255) NOT NULL,
            value VARCHAR(255) NOT NULL,
            contact_id INT NOT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql('CREATE INDEX IDX_D728A71DE7A1254A ON communication_channel (contact_id)');
        $this->addSql(<<<SQL
        CREATE TABLE company (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX COMPANY_UNIQ_NAME ON company (name)');
        $this->addSql(<<<SQL
        CREATE TABLE company_project (
            company_id INT NOT NULL,
            project_id INT NOT NULL,
            PRIMARY KEY (company_id, project_id)
        )
        SQL);
        $this->addSql('CREATE INDEX IDX_FE1CA39979B1AD6 ON company_project (company_id)');
        $this->addSql('CREATE INDEX IDX_FE1CA39166D1F9C ON company_project (project_id)');
        $this->addSql(<<<SQL
        CREATE TABLE contact (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            first_name VARCHAR(255) NOT NULL,
            last_name VARCHAR(255) NOT NULL,
            company_id INT DEFAULT NULL,
            PRIMARY KEY (id)
        )
        SQL);
        $this->addSql('CREATE INDEX IDX_4C62E638979B1AD6 ON contact (company_id)');
        $this->addSql('ALTER TABLE communication_channel ADD CONSTRAINT FK_D728A71DE7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company_project ADD CONSTRAINT FK_FE1CA39979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_project ADD CONSTRAINT FK_FE1CA39166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE communication_channel DROP CONSTRAINT FK_D728A71DE7A1254A');
        $this->addSql('ALTER TABLE company_project DROP CONSTRAINT FK_FE1CA39979B1AD6');
        $this->addSql('ALTER TABLE company_project DROP CONSTRAINT FK_FE1CA39166D1F9C');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638979B1AD6');
        $this->addSql('DROP TABLE communication_channel');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE company_project');
        $this->addSql('DROP TABLE contact');
    }
}
