<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000009 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'File';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE file (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              public_id UUID NOT NULL,
              storage INT NOT NULL,
              uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              original_file_name VARCHAR(255) NOT NULL,
              extension VARCHAR(255) NOT NULL,
              mime_type VARCHAR(255) DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FILE_STORAGE ON file (storage)');
        $this->addSql('CREATE UNIQUE INDEX FILE_UNIQ_PUBLIC_ID ON file (public_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE file');
    }
}
