<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Document and document version';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE document (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              current_version_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8698A769407EE77 ON document (current_version_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE document_tag (
              document_id INT NOT NULL,
              tag_id INT NOT NULL,
              PRIMARY KEY (document_id, tag_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_D0234567C33F7837 ON document_tag (document_id)');
        $this->addSql('CREATE INDEX IDX_D0234567BAD26311 ON document_tag (tag_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE document_version (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              version_number INT NOT NULL,
              note TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              document_id INT NOT NULL,
              file_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B73751F93CB796C ON document_version (file_id)');
        $this->addSql('CREATE INDEX IDX_DOCUMENT_VERSION_DOCUMENT ON document_version (document_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX DOCUMENT_VERSION_UNIQ_DOC_VERSION ON document_version (document_id, version_number)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE project_document (
              project_id INT NOT NULL,
              document_id INT NOT NULL,
              PRIMARY KEY (project_id, document_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_E52701AD166D1F9C ON project_document (project_id)');
        $this->addSql('CREATE INDEX IDX_E52701ADC33F7837 ON project_document (document_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              document
            ADD
              CONSTRAINT FK_D8698A769407EE77 FOREIGN KEY (current_version_id) REFERENCES document_version (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              document_tag
            ADD
              CONSTRAINT FK_D0234567C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              document_tag
            ADD
              CONSTRAINT FK_D0234567BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              document_version
            ADD
              CONSTRAINT FK_1B73751FC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              document_version
            ADD
              CONSTRAINT FK_1B73751F93CB796C FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              project_document
            ADD
              CONSTRAINT FK_E52701AD166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              project_document
            ADD
              CONSTRAINT FK_E52701ADC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE
        SQL);

        $this->addSql(<<<SQL
        ALTER TABLE document
        ADD COLUMN search_data tsvector
        GENERATED ALWAYS AS (
            to_tsvector('simple', COALESCE(name, '') || ' ' || COALESCE(description, ''))
            || to_tsvector('english', COALESCE(name, '') || ' ' || COALESCE(description, ''))
        ) STORED;
        SQL);

        $this->addSql('CREATE INDEX idx_document_search_data ON document USING GIN (search_data);');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A769407EE77');
        $this->addSql('ALTER TABLE document_tag DROP CONSTRAINT FK_D0234567C33F7837');
        $this->addSql('ALTER TABLE document_tag DROP CONSTRAINT FK_D0234567BAD26311');
        $this->addSql('ALTER TABLE document_version DROP CONSTRAINT FK_1B73751FC33F7837');
        $this->addSql('ALTER TABLE document_version DROP CONSTRAINT FK_1B73751F93CB796C');
        $this->addSql('ALTER TABLE project_document DROP CONSTRAINT FK_E52701AD166D1F9C');
        $this->addSql('ALTER TABLE project_document DROP CONSTRAINT FK_E52701ADC33F7837');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_tag');
        $this->addSql('DROP TABLE document_version');
        $this->addSql('DROP TABLE project_document');
    }
}
