<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Project';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_finished BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE989D9B62 ON project (slug)');
        $this->addSql('CREATE TABLE project_managers (project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (project_id, user_id))');
        $this->addSql('CREATE INDEX IDX_94076BDD166D1F9C ON project_managers (project_id)');
        $this->addSql('CREATE INDEX IDX_94076BDDA76ED395 ON project_managers (user_id)');
        $this->addSql('ALTER TABLE project_managers ADD CONSTRAINT FK_94076BDD166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_managers ADD CONSTRAINT FK_94076BDDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_managers DROP CONSTRAINT FK_94076BDD166D1F9C');
        $this->addSql('ALTER TABLE project_managers DROP CONSTRAINT FK_94076BDDA76ED395');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_managers');
    }
}
