<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version00000000000006 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Form submission';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE form_submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data JSONB NOT NULL, field_names JSONB NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, form_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2C216675FF69B7D ON form_submission (form_id)');
        $this->addSql('ALTER TABLE form_submission ADD CONSTRAINT FK_D2C216675FF69B7D FOREIGN KEY (form_id) REFERENCES form_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE form_definition DROP CONSTRAINT fk_form_definition_project');
        $this->addSql('ALTER TABLE form_definition ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE form_definition ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE form_definition ADD CONSTRAINT FK_61F7634C166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_form_definition_project RENAME TO IDX_61F7634C166D1F9C');
        $this->addSql('ALTER TABLE form_field DROP CONSTRAINT fk_form_field_form_definition');
        $this->addSql('DROP INDEX idx_form_field_display_order');
        $this->addSql('ALTER TABLE form_field ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE form_field ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE form_field ALTER is_required DROP DEFAULT');
        $this->addSql('ALTER TABLE form_field ALTER display_order DROP DEFAULT');
        $this->addSql('ALTER TABLE form_field ADD CONSTRAINT FK_D8B2E19B72C8EE2E FOREIGN KEY (form_definition_id) REFERENCES form_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_form_field_form_definition RENAME TO IDX_D8B2E19B72C8EE2E');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE form_submission DROP CONSTRAINT FK_D2C216675FF69B7D');
        $this->addSql('DROP TABLE form_submission');
        $this->addSql('ALTER TABLE form_definition DROP CONSTRAINT FK_61F7634C166D1F9C');
        $this->addSql('ALTER TABLE form_definition ALTER id SET DEFAULT nextval(\'form_definition_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE form_definition ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE form_definition ADD CONSTRAINT fk_form_definition_project FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_61f7634c166d1f9c RENAME TO idx_form_definition_project');
        $this->addSql('ALTER TABLE form_field DROP CONSTRAINT FK_D8B2E19B72C8EE2E');
        $this->addSql('ALTER TABLE form_field ALTER id SET DEFAULT nextval(\'form_field_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE form_field ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE form_field ALTER is_required SET DEFAULT false');
        $this->addSql('ALTER TABLE form_field ALTER display_order SET DEFAULT 0');
        $this->addSql('ALTER TABLE form_field ADD CONSTRAINT fk_form_field_form_definition FOREIGN KEY (form_definition_id) REFERENCES form_definition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_form_field_display_order ON form_field (display_order)');
        $this->addSql('ALTER INDEX idx_d8b2e19b72c8ee2e RENAME TO idx_form_field_form_definition');
    }
}
